---
title: "MIS 64060 Assignment 3"
author: "Antonio Garlisi"
date: "2022-10-13"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
```

```{r import data}
library(caret)
library(e1071)
library(reshape)

universal.df <- read.csv("C:\\Users\\Andrew Garlisi\\Downloads\\UniversalBank.csv" , header=TRUE, stringsAsFactors=FALSE)
```

```{r Partition Data}
dim(universal.df)              # number of observations and columns  

t(t(names(universal.df)))   # list of the variables (column head) 

#partition the data 

set.seed(1)   
train.index <- sample(row.names(universal.df), 0.6*dim(universal.df)[1])               # 60 % is in train set 

valid.index <- setdiff(row.names(universal.df), train.index)             # remaining (40 % ) is in validation set

train.df <- universal.df[train.index,c(1:14)]

valid.df <- universal.df[valid.index,c(1:14)]

```

```{r A - Create Pivot Table - table() method}

tableA <- addmargins(table(train.df$Online,train.df$CreditCard,train.df$Personal.Loan))
tableA
```

```{r B - Classifying the Customer}
ProbCCOnlineLoan <- (46/513)
ProbCCOnlineLoan

#The probability of the customer accepting the personal loan offer if they have a credit card and using online banking services is roughly 9% (46 divided by 513)
```

```{r C1 - Create Pivot Table for Loan (rows) and Online (columns)}
Table1c <- addmargins(table(train.df$Online,train.df$Personal.Loan))
Table1c
```

```{r C2 - Create Pivot Table for Loan (rows) and Online (columns)}
Table2c <- addmargins(table(train.df$CreditCard,train.df$Personal.Loan))
Table2c
```

```{r Di Compute Quantities}
#D i.
ProbCCLoan <- Table2c[2,2]/Table2c[3,2]
ProbCCLoan
#The probability of being a credit card holders from loan acceptors is roughly 27% (81/[299])
```

```{r Dii Compute Quantities}
#D ii.
ProbOnlineLoan <- Table1c[2,2]/Table1c[3,2]
ProbOnlineLoan
#ii. The probability of having online banking from from loan acceptors is roughly 58% (174/[299])

```

```{r Diii Compute Quantities}
#D iii.
ProbLoan <- Table1c[3,2]/Table1c[3,3]
ProbLoan
#iii. The probability of Loan=1 is 100% for loan acceptors (299/299)
```

```{r Div Compute Quantities}
#D iv.
ProbCCNoLoan <- Table2c[2,1]/Table2c[3,1]
ProbCCNoLoan
#iv. The probability of having a credit card out of the group that did not accept the loan is roughly 29% (775/2701)
```

```{r Dv Compute Quantities}
#D v.
ProbOnlineNoLoan <-Table1c[2,1]/Table1c[3,1]
ProbOnlineNoLoan

#v. The probability of having online banking activity out of the group that did not accept the loan is roughly 60% (1619/2701)
```

```{r Dvi Compute Quantities}
#D vi.
ProbNoLoan <- Table1c[3,1]/Table1c[3,3]
ProbNoLoan
#vi. vi. The probability of not being in the group that accepted the loan is roughly 90% (2701/3000) 
```

```{r E Compute Naive Bayes Probability}
NaiveBayesProb <- (ProbCCLoan*ProbOnlineLoan*ProbLoan)/((ProbCCLoan*ProbOnlineLoan*ProbLoan)/(ProbCCNoLoan*ProbOnlineNoLoan*ProbNoLoan))
NaiveBayesProb
#The Naives Bayes probability is roughly 15%
```

```{r F1 Compare Probabilities - Pivot Table Prob}
ProbCCOnlineLoan
#Probability from pivot tables was roughly 9%
```

```{r F2 Compare Probabilities - Naive Bayes}
NaiveBayesProb
#Probability from Naive Bayes was roughly 15%
```

```{r F3 Compare Probabilities}
#The probability from the pivot tables is more accurate as it is a closer reflection of the probability of loan acceptance across the entire data set.
ProbLoan
```

```{r G Entries Needed}
#In order to calculate the probability of the loan being accepted under the conditions ofhaving a credit card user and using online banking can be calculated using the entries above for ProbCCLoan (calculated in D i) and ProbOnlineLoan (calculated in D ii).

ProbG <- ProbCCLoan*ProbOnlineLoan
ProbG

#The result is very similar to the results of the Naive Bayes analysis calulated above in E
```
